administrador/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('clientes','ClienteController@verClientes');
Route::get('pedidos','PedidoController@verPedidos');
Route::resource('productos', 'ProductoController');

administrador/app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $primaryKey='Id_cliente';

    public function pedido()
    {
        return $this->hasMany('App\Pedido');
    }
}

administrador/app/Pedido.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pedido extends Model
{
    protected $primaryKey='Id_pedido';

    public function cliente()
    {
        return $this->belongsTo('App\Cliente','Id_cliente');
    }
    
    public function producto()
    {
        return $this->hasMany('App\Producto','Id_producto','Id_producto');
    }
}

administrador/app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $primaryKey='Id_producto';

    public function pedido()
    {
        return $this->belongsTo('App\Pedido');
    }
}

administrador/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

administrador/app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;

class ClienteController extends Controller
{
    public function verClientes(){
        $clientes = Cliente::orderBy('Id_cliente','desc')->paginate(5);
        return view('clientes.clientes',compact('clientes'));
    }
}

administrador/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

administrador/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

administrador/app/Http/Controllers/PedidoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pedido;

class PedidoController extends Controller
{
    public function verPedidos(){
        $pedidos = Pedido::orderBy('Id_pedido','desc')->paginate(5);
        return view('pedidos.pedidos',compact('pedidos'));
    }

}

administrador/app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Producto;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productos = Producto::orderBy('Id_producto','desc')->paginate(5);
        return view('productos.productos',compact('productos'));
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('productos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $producto=new Producto();
        $request->validate([
            'Nombre_producto'=>'required|min:5|max:30',
            'Precio_producto'=>'required|numeric',
            'Tipo_producto'=>'required|min:5|max:30',
            'Modelo_producto'=>'mimes:jpeg,png',
            'Descripcion_producto'=>'required|min:5',
        ]);
        $producto->Nombre_producto=$request->input('Nombre_producto');
        $producto->Precio_producto=$request->input('Precio_producto');
        $producto->Tipo_producto=$request->input('Tipo_producto');
        $producto->Descripcion_producto=$request->input('Descripcion_producto');
        $producto->Fecha_registro=date('Y-m-d H:i:s');
        $modelo = $request->file('Modelo_producto');
        if ($modelo) {
            $modelo_path = time() . $modelo->getClientOriginalName();
            $modelo->move(public_path().'/images/productos/',$modelo_path);
            $producto->Modelo_producto = '/images/productos/'.$modelo_path;
        }
        $producto->save();
        return redirect()->route('productos.index')->with(array('message' => 'Producto añadido correctamente!'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Producto $producto)
    {
        return view('productos.edit',compact('producto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Producto $producto)
    {
        $request->validate([
            'Nombre_producto'=>'required|min:5|max:30',
            'Precio_producto'=>'required|numeric',
            'Tipo_producto'=>'required|min:5|max:30',
            'Modelo_producto'=>'mimes:jpeg,png',
            'Descripcion_producto'=>'required|min:5',
        ]);
        $producto->Nombre_producto=$request->input('Nombre_producto');
        $producto->Precio_producto=$request->input('Precio_producto');
        $producto->Tipo_producto=$request->input('Tipo_producto');
        $producto->Descripcion_producto=$request->input('Descripcion_producto');
        $producto->Fecha_registro=date('Y-m-d H:i:s');
        $modelo = $request->file('Modelo_producto');
        if ($modelo) {
            $modelo_path = time() . $modelo->getClientOriginalName();
            $modelo->move(public_path().'/images/productos/',$modelo_path);
            $producto->Modelo_producto = '/images/productos/'.$modelo_path;
        }
        $producto->save();
        return redirect()->route('productos.index')->with(array('message' => 'Producto actualizado correctamente!'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Producto $producto)
    {
        $producto->delete();
        return redirect()->route('productos.index')->with(array('message' => 'El producto ha sido eliminado correctamente!'));

    }
}

administrador/resources/views/clientes/clientes.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div >
        @if (Auth::check())            
            <h1 class="text-center">Clientes</h1>
            <hr>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Email</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clientes as $cliente)
                    <tr>
                    <th scope="row">{{$cliente->Id_cliente}}</th>
                    <td>{{$cliente->Nombre_cliente}}</td>
                    <td>{{$cliente->Apellidos_cliente}}</td>
                    <td>{{$cliente->Email_cliente}}</td>
                    </tr>
                        
                    @endforeach
                </tbody>
            </table>
            {{$clientes->links()}}   
                
            @else
            <div class="alert alert-danger">
                <h1>Debes estar logeado para ver el contenido</h1>
            </div>
                
        @endif
    </div>
</div>
@endsection

administrador/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <h1 class="text-center">Bienvenido</h1>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h2 class="text-center">Has Iniciado sesion {{Auth::user()->name}}</h2>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

administrador/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Administrador</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('css/style.css')}}">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Inicio
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown"><a class="nav-link" href="{{url('clientes')}} ">Clientes</a></li> 
                            <li class="nav-item dropdown"><a class="nav-link" href="{{url('productos')}} ">Productos</a></li> 
                            <li class="nav-item dropdown"><a class="nav-link" href="{{url('pedidos')}} ">Pedidos</a></li> 
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

administrador/resources/views/pedidos/pedidos.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div >
        @if (Auth::check())            
            <h1 class="text-center">Pedidos</h1>
            <hr>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Costo unitario</th>
                    <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody class="productos">
                    @foreach ($pedidos as $pedido)
                    <tr>
                    <th scope="row">{{$pedido->Id_pedido}}</th>
                    <td>{{$pedido->cliente->Nombre_cliente . ' '. $pedido->cliente->Apellidos_cliente}}</td>

                    @foreach ($pedido->producto as $producto)
                        <td><img src="{{$producto->Modelo_producto}}" alt=""></td>
                    @endforeach
                    
                    <td>{{$pedido->Descripcion_pedido}}</td>
                    <td>{{$pedido->Fecha_pedido}}</td>
                    <td>{{$pedido->Cantidad_producto}}</td>
                    <td>{{$pedido->Costo_unitario}}</td>
                    <td>{{$pedido->Total}}</td>
                    </tr>
                        
                    @endforeach
                </tbody>
            </table>
            {{$pedidos->links()}}   
                
            @else
            <div class="alert alert-danger">
                <h1>Debes estar logeado para ver el contenido</h1>
            </div>
                
        @endif
    </div>
</div>
@endsection

administrador/resources/views/productos/create.blade.php
@extends('layouts.app')

@section('content')
<h1 class="text-center">Agregar Producto</h1>
<hr>
<div class="container">
    <div>
        @if (Auth::check())
        <form action="{{route('productos.store')}} " method="POST" enctype="multipart/form-data">
            @csrf
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Nombre_producto">Nombre</label>
                        <input type="text" name="Nombre_producto" id="Nombre_producto" placeholder="Nombre del producto" class="form-control">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="Precio_producto">Precio</label>
                        <input type="text" name="Precio_producto" id="Precio_producto" placeholder="Precio del producto" class="form-control" placeholder="0">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="Modelo_producto">Modelo</label>
                        <input type="file" name="Modelo_producto" id="Modelo_producto" class="form-control-file">
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Tipo_producto">Tipo</label>
                        <input type="text" name="Tipo_producto" id="Tipo_producto" placeholder="Tipo del producto" class="form-control">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Descripcion_producto">Descripcion</label>
                        <textarea name="Descripcion_producto" id="Descripcion_producto" class="form-control"></textarea>
                    </div>
                </div>
                <input type="submit" value="Guardar Producto"class="btn btn-outline-success">
            </div>
        </form>
        @else
            <div class="alert alert-danger">
                <h1>Debes estar logeado para ver el contenido</h1>
            </div>

        @endif
              
    </div>
</div>
@endsection

administrador/resources/views/productos/edit.blade.php
@extends('layouts.app')

@section('content')
<h1 class="text-center">Editar Producto</h1>
<hr>
<div class="container">
    <div>
        @if (Auth::check())
        <form action="{{route('productos.update',$producto->Id_producto)}} " method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Nombre_producto">Nombre</label>
                        <input type="text" name="Nombre_producto" id="Nombre_producto" placeholder="Nombre del producto" class="form-control" value="{{$producto->Nombre_producto}} ">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="Precio_producto">Precio</label>
                        <input type="text" name="Precio_producto" id="Precio_producto" placeholder="Precio del producto" class="form-control" placeholder="0" value="{{$producto->Precio_producto}} ">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="Modelo_producto">Modelo</label>
                        <input type="file" name="Modelo_producto" id="Modelo_producto" class="form-control-file">
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Tipo_producto">Tipo</label>
                        <input type="text" name="Tipo_producto" id="Tipo_producto" placeholder="Tipo del producto" class="form-control" value="{{$producto->Tipo_producto}} ">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Descripcion_producto">Descripcion</label>
                        <textarea name="Descripcion_producto" id="Descripcion_producto" class="form-control">{{$producto->Descripcion_producto}}</textarea>
                    </div>
                </div>
                <input type="submit" value="Actualizar Producto"class="btn btn-outline-success">
            </div>
        </form>
        @else
            <div class="alert alert-danger">
                <h1>Debes estar logeado para ver el contenido</h1>
            </div>

        @endif
              
    </div>
</div>
@endsection

administrador/resources/views/productos/productos.blade.php
@extends('layouts.app')

@section('content')
<h1 class="text-center">Productos</h1>
<hr>
<div class="container">
    <div>
        @if (Auth::check())
            @if (session('message'))
                <div class="alert alert-success">
                    {{session('message')}}
                </div>
            @endif
    
        <a href="{{route('productos.create')}} " class="btn btn-outline-primary mb-3">Añadir producto</a>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Precio</th>
                <th scope="col">Modelo</th>
                <th scope="col">Tipo</th>
                <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody class="productos">
                @foreach ($productos as $producto)
                <tr>
                <th scope="row">{{$producto->Id_producto}}</th>
                <td>{{$producto->Nombre_producto}}</td>
                <td>{{$producto->Descripcion_producto}}</td>
                <td>$ {{$producto->Precio_producto}}</td>
                <td><img class="img-fluid img-thumbnail" src="{{$producto->Modelo_producto}}" alt=""></td>
                <td>{{$producto->Tipo_producto}}</td>
                <td>
                    <a href="{{route('productos.edit',$producto->Id_producto)}} " class="btn btn-outline-info mb-3">Editar</a>
                    <form action="{{route('productos.destroy', $producto->Id_producto)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <input type="submit" value="Eliminar" class="btn btn-outline-danger" onclick="return confirm('Seguro que desear eliminar este producto?')">
                        {{-- <a href="{{route('productos.destroy', $producto->Id_producto)}} " class="btn btn-outline-danger">Eliminar</a> --}}
                    </form>
                </td>
                </tr>
                    
                @endforeach
            </tbody>
            </table>
            {{$productos->links()}}   

        @else
            <div class="alert alert-danger">
                <h1>Debes estar logeado para ver el contenido</h1>
            </div>

        @endif
              
    </div>
</div>
@endsection